name: UpLeveled Preflight check
on: [push]

jobs:
  Preflight-check:
    name: UpLeveled Preflight check
    runs-on: ubuntu-latest

    steps:
      - name: Get UpLeveled check image
        run: docker pull ghcr.io/upleveled/preflight
      - name: Run Get UpLeveled check image
        run: docker run ghcr.io/upleveled/preflight https://github.com/upleveled/portfolio-cms
