name: UpLeveled Preflight check
on: [push]

jobs:
  Preflight-check:
    name: UpLeveled Preflight check
    runs-on: ubuntu-latest

    steps:
      - name: Get UpLeveled check image
        run: docker pull ghcr.io/upleveled/preflight
      - name: Run Get UpLeveled check image
        id: preflight-check
        run: |
          MY_STRING=$(docker run ghcr.io/upleveled/preflight https://github.com/upleveled/portfolio-cms)
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo "::set-output name=preflight::$MY_STRING"
      - name: step-2
        run: echo "${{ steps.preflight-check.outputs.preflight }}"
